name: SMB CI Pipeline (Develop)

on:
  push:
    branches:
      - develop

jobs:
  develop-tests:
    name: Testes no ambiente de desenvolvimento
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rodando testes
        run: |
          echo "Executando testes no DEVELOP"
          # Aqui você coloca:
          # composer install
          # php artisan test
          # npm install
          # npm run build (opcional)
